import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../components/Card';
import { Button } from '../components/Button';
import { FileText, Download, BarChart2, Shield } from 'lucide-react';

export function Reports() {
  const [generating, setGenerating] = useState(false);

  const handleDownload = () => {
    setGenerating(true);
    setTimeout(() => {
      setGenerating(false);
      // Dummy download logic
      const link = document.createElement('a');
      link.href = 'data:text/plain;charset=utf-8,' + encodeURIComponent('Dummy Security Report Content');
      link.download = 'Security_Report_June_2026.pdf';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }, 1500);
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white">Reports & Analytics</h1>
        <p className="text-slate-400 text-sm mt-1">Generate and download comprehensive security reports.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="w-5 h-5 text-brand-cyan" />
              Executive Summary
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-slate-400 mb-6">High-level overview of security posture, blocked threats, and overall risk score.</p>
            <Button variant="outline" className="w-full" onClick={handleDownload} disabled={generating}>
              <Download className="w-4 h-4 mr-2" />
              {generating ? 'Generating...' : 'Download PDF'}
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <BarChart2 className="w-5 h-5 text-brand-purple" />
              Threat Analytics
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-slate-400 mb-6">Detailed breakdown of attack vectors, malware types, and targeted assets.</p>
            <Button variant="outline" className="w-full" onClick={handleDownload} disabled={generating}>
              <Download className="w-4 h-4 mr-2" />
              {generating ? 'Generating...' : 'Download PDF'}
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-brand-blue" />
              Compliance Report
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-slate-400 mb-6">Audit logs and vulnerability status mapped to SOC2 and ISO 27001 controls.</p>
            <Button variant="outline" className="w-full" onClick={handleDownload} disabled={generating}>
              <Download className="w-4 h-4 mr-2" />
              {generating ? 'Generating...' : 'Download PDF'}
            </Button>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Generated Report History</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="w-full text-sm text-left">
              <thead className="text-xs text-slate-400 uppercase bg-slate-800/50">
                <tr>
                  <th className="px-4 py-3 rounded-tl-lg">Report Name</th>
                  <th className="px-4 py-3">Type</th>
                  <th className="px-4 py-3">Generated By</th>
                  <th className="px-4 py-3 rounded-tr-lg">Date</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-slate-800 hover:bg-slate-800/30">
                  <td className="px-4 py-3 font-medium text-white flex items-center gap-2">
                    <FileText className="w-4 h-4 text-slate-400" />
                    Monthly_Threat_Summary_May.pdf
                  </td>
                  <td className="px-4 py-3 text-slate-400">Threat Analytics</td>
                  <td className="px-4 py-3 text-slate-400">System Admin</td>
                  <td className="px-4 py-3 text-slate-400">01 Jun 2026</td>
                </tr>
                <tr className="hover:bg-slate-800/30">
                  <td className="px-4 py-3 font-medium text-white flex items-center gap-2">
                    <FileText className="w-4 h-4 text-slate-400" />
                    Q1_Compliance_Audit.pdf
                  </td>
                  <td className="px-4 py-3 text-slate-400">Compliance</td>
                  <td className="px-4 py-3 text-slate-400">Security Officer</td>
                  <td className="px-4 py-3 text-slate-400">15 Apr 2026</td>
                </tr>
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
